spring:
  application:
    name: diploma
  data:
    mongodb:
      uri: mongodb://localhost:27017/MongoLocal_2_uri
      database: MongoLocal_2_uri
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        generate_statistics: true
        bytecode:
          use_reflection_optimizer: true
        show_sql: false
    hibernate:
      ddl-auto: none
    open-in-view: false
  config:
    import: optional:configserver:${CONFIG_SERVER:http://localhost:8888/}
  main:
    allow-bean-definition-overriding: true

server:
  port: 8070
eureka:
  client:
    healthcheck:
      enabled: true
logging:
  level:
    org: INFO
management:
  metrics:
    distribution:
      percentiles:
        http.server.requests: 0.99, 0.95, 0.9, 0.7, 0.5
      percentiles-histogram:
        http.server.requests: true
      slo:
        http.server.requests: 300ms,500ms,1s,2s
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: prometheus, metrics
openai:
  api-key: hidden

springdoc:
  api-docs:
    path: /api-docs
