services:
  discovery:
    container_name: discovery
    image: eatcodepray/bnb-diploma-discovery
    platform: linux/amd64
    ports:
      - "8761:8761"

  config-server:
    container_name: config-server
    image: eatcodepray/bnb-diploma-config-server
    platform: linux/amd64
    ports:
      - "8888:8888"
    volumes:
      - ./config-data:/var/config-data
    environment:
      - CONFIG_FOLDER=/var/config-data
    depends_on:
      - discovery

  migration:
    container_name: bnb_db
    image: eatcodepray/bnb-diploma-migration:latest
    platform: linux/amd64
    ports:
      - "5432:5432"
    depends_on:
      - config-server
  test_db:
    container_name: bnb_test_db
    image: eatcodepray/bnb-diploma-migration:test
    platform: linux/amd64
    ports:
      - "5433:5432"
    depends_on:
      - config-server