spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/MongoLocal_2_uri
  datasource:
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/bnb_db
    hikari:
      connection-test-query: SELECT 1
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
